### ISSUE TITLE
UnboundLocalError: local variable 'days' referenced before assignment

### ISSUE THREAD

**Issue by avico78** [toyama0919/awscost#20]
Hi, 
Can you explain how to set my aws account detail so could connect to it?

second, Trying to run the example :

```
from awscost.cost_explorer import CostExplorer
from dateutil.relativedelta import relativedelta
from datetime import datetime

start = (datetime.today() - relativedelta(months=3)).strftime("%Y-%m-01")
end = datetime.today().strftime("%Y-%m-01")

cost_explorer = CostExplorer(
    "MONTHLY", start, end, dimensions=["SERVICE"], metrics="UnblendedCost"
).get_cost_and_usage_total_and_group_by()

# return dict data. 
cost_explorer # =>

```
getting:
```
Traceback (most recent call last):
  File "c:\Users\avico\OneDrive\Desktop\בסד\5_or7.py", line 8, in <module>
    cost_explorer = CostExplorer(
  File "C:\Users\avico\AppData\Local\Programs\Python\Python310\lib\site-packages\awscost\cost_explorer.py", line 50, in __init__
    start or profile.get("start") or DateUtil.get_start(self.granularity, point)
  File "C:\Users\avico\AppData\Local\Programs\Python\Python310\lib\site-packages\awscost\date_util.py", line 16, in get_start
    start_datetime = datetime.today() - timedelta(days=days)
UnboundLocalError: local variable 'days' referenced before assignment
```

**Comment by toyama0919** [comment]
Sorry for the late reply!
I'll check it out.

**Comment by toyama0919** [comment]
READMEのAPIの呼び方が間違ってましたね。。
すぐREADMEを直します
ちなみに、これでうまくいきます

```
from awscost.cost_explorer import CostExplorer
from dateutil.relativedelta import relativedelta
from datetime import datetime

start = (datetime.today() - relativedelta(months=3)).strftime("%Y-%m-01")
end = datetime.today().strftime("%Y-%m-01")

cost_explorer = CostExplorer(
    granularity="MONTHLY", start=start, end=end, dimensions=["SERVICE"], metrics="UnblendedCost"
).get_cost_and_usage_total_and_group_by()

# return dict data.
print(cost_explorer)

```
